#!/bin/bash

set -e
set -x

SHA1=`git rev-parse --short HEAD | tr -d "\n"`

if [ ! "$CONTAINER_URL" ]; then
  # if CONTAINER_URL isn't set, a non ci build is running and it really doesn't matter
  CONTAINER_URL=ci
fi

docker run --rm -i -t \
  -v $PWD:/build \
  -w /build \
  node:0.10.38 /bin/sh -c "npm prune && npm install && npm run build"

docker build -t $CONTAINER_URL:$SHA1 .

if [ ! -z "$PUBLISH" ]; then
  echo "--- Publishing container"
  if [ "$BUILDKITE_BRANCH" == "master" ]; then
    time docker push $CONTAINER_URL:$SHA1
  fi
fi
