#!/bin/bash

set -e
set -x


export parent_dir=`pwd`

if [ ! -d $parent_dir/dist/.git ]; then
  rm -rf $parent_dir/dist
fi

echo "--- Fetching existing repo"
if [ -d "$parent_dir/dist" ]; then
    cd $parent_dir/dist
    git fetch origin
    git checkout -f origin/gh-pages
    git checkout -B gh-pages
else
    cd $parent_dir
    git clone https://github.com/macropodhq/macropod-components.git dist -b gh-pages --single-branch
fi

docker run --rm -i -t \
  -v $PWD:/build \
  -w /build \
  node:0.10.38 /bin/sh -c "npm prune && npm install && npm run build"

cd $parent_dir/dist
git commit -a -m "Publish"
if [ ! -z "$PUBLISH" ]; then
  git push -f git@github.com:macropodhq/macropod-components.git gh-pages
fi
