#!/bin/bash

set -e
set -x


export parent_dir=`pwd`

if [ !-d $parent_dir/dist/.git ]; then
  rm -rf $parent_dir/dist
fi

echo "--- Fetching existing repo"
if [ -d "$parent_dir/dist" ]; then
    cd $parent_dir/dist
    git fetch origin
    git checkout -f origin/gh-pages
    git commit -a -m "Publish"
    git push -f origin gh-pages
else
    cd $parent_dir
    git clone https://github.com/macropodhq/macropod-components.git dist -b gh-pages --single-branch
fi

docker run --rm -i -t \
  -v $PWD:/build \
  -w /build \
  node:0.10.38 /bin/sh -c "npm prune && npm install && npm run build"

